"""Pure text/JSON templates for generated host files. No filesystem or core dependency:
every function here is a string/dict builder so it can be unit-tested without a project on disk.
"""
from __future__ import annotations

import json
import shlex
from typing import Any, Dict, List

HEARMEMORY_MARKER = "hearmemory"
BEGIN_MARKER = "<!-- hearmemory:begin (managed by hearmemory; remove with `hearmemory uninstall`) -->"
END_MARKER = "<!-- hearmemory:end -->"
SH_BEGIN_MARKER = "# hearmemory:begin (generated by hearmemory; remove with `hearmemory uninstall`)"
SH_END_MARKER = "# hearmemory:end"


class UnsafePathError(ValueError):
    """A project / interpreter path that cannot be written safely into generated shell or TOML text
    (control characters such as a newline). `hearmemory init` refuses instead of generating broken hooks."""


def check_safe_path(value: str, what: str = "path") -> str:
    """every path that goes into generated shell / TOML text is quoted (shlex.quote /
    json.dumps), which handles spaces, quotes, `$` and backticks. Control characters (newline, tab,
    NUL, DEL, ...) cannot be represented reliably in every consumer (a hook runner splitting lines, a
    TOML parser), so they are rejected up front."""
    s = str(value)
    if any(ord(ch) < 0x20 or ord(ch) == 0x7F for ch in s):
        raise UnsafePathError(f"hearmemory cannot install into a {what} containing control characters "
                              f"(e.g. a newline): {s!r}. Rename the directory and run `hearmemory init` again.")
    return s


def q(value: str) -> str:
    """Shell-quote one word for generated POSIX sh text."""
    return shlex.quote(str(value))


def toml_str(value: str) -> str:
    """A TOML basic string for `value`. JSON string escaping is a subset of TOML basic-string
    escaping, so json.dumps gives a valid TOML string for any control-character-free text."""
    return json.dumps(str(value), ensure_ascii=False)


def toml_str_array(values: List[str]) -> str:
    return "[" + ",".join(toml_str(v) for v in values) + "]"


def hearmemory_argv(python: str, root: str, *rest: str) -> List[str]:
    # NOTE: `--project` is a top-level `hearmemory` option (before the subcommand).
    return [str(python), "-m", "hearmemory", "--project", str(root), *rest]


def hook_command(python: str, root: str, host: str, event: str) -> str:
    """the one-line command every generated hook config runs (hosts run it through `sh -c`).
    Every word is shlex-quoted (a project path with a `'` used to make every hook a shell
    syntax error -- exit 2 under dash, which Claude Code treats as "block"). `|| true` guarantees a
    missing interpreter never surfaces as an error to the host; blocking is expressed through stdout
    JSON (Claude/Cursor) or the git hook's own exit code, never through this command failing."""
    return shlex.join(hearmemory_argv(python, root, "hook", host, event)) + " 2>/dev/null || true"


# --------------------------------------------------------------------------- Claude Code
def claude_mcp_json(python: str, root: str) -> Dict[str, Any]:
    # NOTE: `--project` is a top-level `hearmemory` option (before the subcommand), not a `mcp`
    # subcommand flag - it must come before "mcp" in argv or argparse rejects it.
    return {"mcpServers": {"hearmemory": {"type": "stdio", "command": python,
                                     "args": ["-m", "hearmemory", "--project", root, "mcp", "--host", "claude"]}}}


def claude_hook_entry(python: str, root: str, host: str, event: str, timeout: int, matcher: str | None) -> Dict[str, Any]:
    entry: Dict[str, Any] = {"hooks": [{"type": "command", "command": hook_command(python, root, host, event),
                                        "timeout": timeout}]}
    if matcher is not None:
        entry["matcher"] = matcher
    return entry


def claude_settings_json(python: str, root: str) -> Dict[str, Any]:
    from hearmemory.interfaces import CLAUDE_CAPTURE_EVENTS, CLAUDE_TOOL_MATCHER

    hooks: Dict[str, Any] = {
        "SessionStart": [claude_hook_entry(python, root, "claude", "SessionStart", 10,
                                            "startup|resume|clear|compact")],
        "UserPromptSubmit": [claude_hook_entry(python, root, "claude", "UserPromptSubmit", 5, None)],
        "PreToolUse": [claude_hook_entry(python, root, "claude", "PreToolUse", 10, "Bash")],
        "SubagentStart": [claude_hook_entry(python, root, "claude", "SubagentStart", 5, None)],
        "SubagentStop": [claude_hook_entry(python, root, "claude", "SubagentStop", 5, None)],
        "Stop": [claude_hook_entry(python, root, "claude", "Stop", 5, None)],
    }
    # PostToolUse and PostToolUseFailure are generated from the SAME matcher
    # constant, in the same loop, so they can never drift apart.
    for event in CLAUDE_CAPTURE_EVENTS:
        hooks[event] = [claude_hook_entry(python, root, "claude", event, 5, CLAUDE_TOOL_MATCHER)]
    return {"hooks": hooks}


def claude_cmd_argv(root: str) -> List[str]:
    """`hearmemory host claude-cmd` and launch.sh's exec line: session-only Claude Code flags."""
    return ["claude", "--mcp-config", f"{root}/.hearmemory/host/claude/mcp.json",
            "--settings", f"{root}/.hearmemory/host/claude/settings.json"]


def claude_launch_sh(python: str, root: str) -> str:
    return (
        "#!/bin/sh\n"
        + shlex.join(hearmemory_argv(python, root, "worker", "--spawn", "--launched-by", "launch.sh"))
        + " >/dev/null 2>&1 || true\n"
        + "exec " + shlex.join(claude_cmd_argv(root)) + ' "$@"\n'
    )


# --------------------------------------------------------------------------- Codex
def codex_agents_block() -> str:
    return (
        f"{BEGIN_MARKER}\n"
        "## Shared project memory (hearmemory)\n"
        "- At the start of a task run `hearmemory recall --brief` (or call the hearmemory_recall tool with "
        "brief=true) and read it.\n"
        "- Items tagged [REFUTED] or [DISPUTED] must not be relied on without re-checking.\n"
        "- When you reach a conclusion (root cause, fix, test status), record it: "
        '`hearmemory record --kind claim "<one sentence>"`.\n'
        "- Before `git commit` or your final answer, run `hearmemory check --staged` (or "
        '`hearmemory check --text "<conclusion>"`).\n'
        f"{END_MARKER}\n"
    )


def _codex_mcp_args(root: str) -> List[str]:
    return ["-m", "hearmemory", "--project", str(root), "mcp", "--host", "codex"]


def codex_launch_sh(python: str, root: str) -> str:
    # Every `-c` value is TOML (json.dumps-escaped strings) inside ONE shell word (shlex.quote);
    # only the session id is interpolated by the shell at launch time (it contains no quotes).
    # Codex runs as a CHILD (no exec) so that, when it exits, this script imports the session's
    # rollout and reconciles HEARMEMORY_SESSION_ID with the rollout session id (Codex has no per-tool hooks
    # usable without user-level config). The exit status of codex is preserved. `trap ':'` keeps this shell
    # alive through Ctrl-C / a closed terminal without changing how codex itself sees those signals (a
    # trapped signal is reset to its default in the child, an ignored one would not be).
    return (
        "#!/bin/sh\n"
        'export HEARMEMORY_SESSION_ID="codex-$(date +%s)-$$"\n'
        + shlex.join(hearmemory_argv(python, root, "worker", "--spawn", "--launched-by", "launch.sh"))
        + " >/dev/null 2>&1 || true\n"
        + "trap ':' INT TERM HUP\n"
        + "codex -c " + q("mcp_servers.hearmemory.command=" + toml_str(python)) + " \\\n"
        + "  -c " + q("mcp_servers.hearmemory.args=" + toml_str_array(_codex_mcp_args(root))) + " \\\n"
        + "  -c 'mcp_servers.hearmemory.env={HEARMEMORY_SESSION_ID=\"'\"$HEARMEMORY_SESSION_ID\"'\"}' \"$@\"\n"
        + "hearmemory_status=$?\n"
        + shlex.join(hearmemory_argv(python, root, "import", "codex")) + ' --launch-session "$HEARMEMORY_SESSION_ID"'
        + " >/dev/null 2>&1 || true\n"
        + shlex.join(hearmemory_argv(python, root, "worker", "--spawn", "--launched-by", "launch.sh:exit"))
        + " >/dev/null 2>&1 || true\n"
        + 'exit "$hearmemory_status"\n'
    )


def codex_cmd_argv(python: str, root: str) -> List[str]:
    """`hearmemory host codex-cmd`: the same argv as codex_launch_sh's exec line, without the session-id
    shell interpolation, as a plain argv list (printed with shlex.join)."""
    return [
        "codex", "-c", "mcp_servers.hearmemory.command=" + toml_str(python),
        "-c", "mcp_servers.hearmemory.args=" + toml_str_array(_codex_mcp_args(root)),
    ]


def codex_hooks_json(python: str, root: str) -> Dict[str, Any]:
    """Experimental (`hearmemory host codex-cmd --hooks`); key names to be confirmed against the local
    Codex CLI version."""
    return {
        "hooks": {
            "SessionStart": [{"command": hook_command(python, root, "codex", "SessionStart")}],
            "Stop": [{"command": hook_command(python, root, "codex", "Stop")}],
        }
    }


# --------------------------------------------------------------------------- Cursor (opt-in)
def cursor_mcp_entry(python: str, root: str) -> Dict[str, Any]:
    return {"command": python, "args": ["-m", "hearmemory", "--project", root, "mcp", "--host", "cursor"]}


def cursor_hooks_json(python: str, root: str) -> Dict[str, Any]:
    def cmd(event: str) -> Dict[str, str]:
        return {"command": hook_command(python, root, "cursor", event)}

    return {
        "version": 1,
        "hooks": {
            "sessionStart": [cmd("sessionStart")],
            "beforeShellExecution": [cmd("beforeShellExecution")],
            "afterShellExecution": [cmd("afterShellExecution")],
            "afterFileEdit": [cmd("afterFileEdit")],
            "afterAgentResponse": [cmd("afterAgentResponse")],
            "stop": [cmd("stop")],
        },
    }


def cursor_rules_mdc() -> str:
    body = codex_agents_block().replace(BEGIN_MARKER + "\n", "").replace(END_MARKER + "\n", "")
    return (
        "---\n"
        "description: hearmemory shared project memory\n"
        "alwaysApply: true\n"
        "---\n\n" + body
    )


# --------------------------------------------------------------------------- git
def git_dispatcher_script() -> str:
    """Lives in the (possibly worktree-shared) git hooks directory. Content is project-agnostic: it
    only looks at the CURRENT worktree's own .hearmemory/host/git/pre-commit, so it is a no-op for any
    worktree that never ran `hearmemory init`."""
    return (
        "#!/bin/sh\n"
        f"{SH_BEGIN_MARKER}\n"
        'HOOK_DIR=$(dirname "$0")\n'
        'if [ -x "$HOOK_DIR/pre-commit.hearmemory-orig" ]; then "$HOOK_DIR/pre-commit.hearmemory-orig" "$@" || exit $?; fi\n'
        '[ -n "$HEARMEMORY_DISABLE" ] && exit 0\n'
        'TOP=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0\n'
        'D="$TOP/.hearmemory/host/git/pre-commit"\n'
        '{ [ -f "$TOP/.hearmemory/VERSION" ] && [ -x "$D" ]; } || exit 0\n'
        '"$D" </dev/null\n'
        '[ $? -eq 1 ] && exit 1\n'
        "exit 0\n"
        f"{SH_END_MARKER}\n"
    )


def git_project_pre_commit_script(root: str, python: str) -> str:
    return (
        "#!/bin/sh\n"
        f"ROOT={q(root)}\n"
        'TOP=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0\n'
        '[ "$(cd "$TOP" && pwd -P)" = "$(cd "$ROOT" 2>/dev/null && pwd -P)" ] || exit 0\n'
        f"PY={q(python)}\n"
        '[ -x "$PY" ] || exit 0\n'
        'exec "$PY" -m hearmemory --project "$ROOT" hook git pre-commit\n'
    )
